const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ['daily_occupancy', 'no_show', 'hotel_occupancy', 'financial', 'checkout_statement'],
    required: true
  },
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  reportDate: {
    type: Date,
    required: true
  },
  dateRange: {
    startDate: Date,
    endDate: Date
  },
  data: {
    type: mongoose.Schema.Types.Mixed,
    required: true
  },
  status: {
    type: String,
    enum: ['generated', 'archived'],
    default: 'generated'
  }
}, {
  timestamps: true
});

reportSchema.index({ type: 1, reportDate: -1 });
reportSchema.index({ generatedBy: 1 });

module.exports = mongoose.model('Report', reportSchema);
